version: "3.7"

services:

  backend:
    build: ./
    container_name: portfolio_backend
    restart: always
    ports:
      - 5000:5000


  nginx_web:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../React-Portfolio/build:/var/www/frontend
    depends_on:
      - backend
    ports:
      - 80:80