"""empty message

Revision ID: 14c32941b999
Revises: 305680fcf892
Create Date: 2020-11-10 17:49:12.543549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c32941b999'
down_revision = '305680fcf892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_project', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_project', 'position')
    # ### end Alembic commands ###
