"""empty message

Revision ID: 305680fcf892
Revises: c9a793d815f8
Create Date: 2020-11-04 18:07:52.981372

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "305680fcf892"
down_revision = "c9a793d815f8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portfolio_link",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=127), nullable=False),
        sa.Column("url", sa.String(length=511), nullable=False),
        sa.Column("portfolio_project_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["portfolio_project_id"], ["portfolio_project.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # op.alter_column('portfolio_project', 'description',
    #            existing_type=sa.NUMERIC(),
    #            nullable=False)
    # op.alter_column('portfolio_project', 'image_path',
    #            existing_type=sa.NUMERIC(),
    #            nullable=False)
    # op.alter_column('portfolio_project', 'name',
    #            existing_type=sa.NUMERIC(),
    #            nullable=False)
    # op.create_unique_constraint('project_image_uc', 'portfolio_project', ['id', 'image_path'])
    # op.create_unique_constraint('project_name_uc', 'portfolio_project', ['id', 'name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("project_name_uc", "portfolio_project", type_="unique")
    op.drop_constraint("project_image_uc", "portfolio_project", type_="unique")
    op.alter_column(
        "portfolio_project", "name", existing_type=sa.NUMERIC(), nullable=True
    )
    op.alter_column(
        "portfolio_project", "image_path", existing_type=sa.NUMERIC(), nullable=True
    )
    op.alter_column(
        "portfolio_project", "description", existing_type=sa.NUMERIC(), nullable=True
    )
    op.drop_table("portfolio_link")
    # ### end Alembic commands ###
