"""Include role and year in portfolio porject

Revision ID: 5126e6d6af2d
Revises: ce5546901c49
Create Date: 2020-11-22 17:43:39.846031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5126e6d6af2d'
down_revision = 'ce5546901c49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_project', sa.Column('role', sa.String(length=255), nullable=True))
    op.add_column('portfolio_project', sa.Column('year', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_project', 'year')
    op.drop_column('portfolio_project', 'role')
    # ### end Alembic commands ###
