"""portfolio_project

Revision ID: 592f72c1f2f8
Revises: 
Create Date: 2020-10-29 21:11:08.542194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592f72c1f2f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('description', sa.String(length=2047), nullable=False),
    sa.Column('image_path', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_project')
    # ### end Alembic commands ###
