"""empty message

Revision ID: 644f8e836f31
Revises: 
Create Date: 2020-10-31 20:47:24.596389

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "644f8e836f31"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "education_section_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("school_name", sa.String(length=127), nullable=False),
        sa.Column("major", sa.String(length=127), nullable=False),
        sa.Column("graduation_month_year", sa.String(length=127), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "school_name", name="id_school_name_uc"),
    )
    op.create_table(
        "job_section_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_name", sa.String(length=127), nullable=False),
        sa.Column("position", sa.String(length=127), nullable=False),
        sa.Column("period_of_working", sa.String(length=511), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "company_name", name="id_company_name_uc"),
    )
    op.create_table(
        "portfolio_project",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=127), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("image_path", sa.String(length=1024), nullable=False),
        sa.Column("notebook_path", sa.String(length=1024), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "image_path", name="project_image_uc"),
    )
    op.create_table(
        "social_link",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=127), nullable=False),
        sa.Column("url", sa.String(length=511), nullable=False),
        sa.Column("class_name", sa.String(length=127), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "name", name="id_name_uc"),
    )
    op.create_table(
        "web_site_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=127), nullable=False),
        sa.Column("avatar_image_path", sa.String(length=1024), nullable=True),
        sa.Column("role", sa.String(length=511), nullable=False),
        sa.Column("role_description", sa.String(length=2047), nullable=False),
        sa.Column("about_me", sa.Text(), nullable=False),
        sa.Column("address", sa.String(length=127), nullable=False),
        sa.Column("website", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("web_site_info")
    op.drop_table("social_link")
    op.drop_table("portfolio_project")
    op.drop_table("job_section_item")
    op.drop_table("education_section_item")
    # ### end Alembic commands ###
