"""empty message

Revision ID: 8cfc85e5f0d6
Revises: 14c32941b999
Create Date: 2020-11-10 18:58:08.353547

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8cfc85e5f0d6'
down_revision = '14c32941b999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education_section_item', sa.Column('position', sa.Integer(), nullable=True))
    op.add_column('job_section_item', sa.Column('order_number', sa.Integer(), nullable=True))
    op.add_column('social_link', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_link', 'position')
    op.drop_column('job_section_item', 'order_number')
    op.drop_column('education_section_item', 'position')
    # ### end Alembic commands ###
