"""empty message

Revision ID: c9d2f1c46d14
Revises: 5126e6d6af2d
Create Date: 2021-01-13 13:03:29.767869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d2f1c46d14'
down_revision = '5126e6d6af2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_site_info', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_site_info', 'email')
    # ### end Alembic commands ###
