"""Add archived

Revision ID: e80921973da5
Revises: c9d2f1c46d14
Create Date: 2021-11-04 15:55:02.304139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e80921973da5'
down_revision = 'c9d2f1c46d14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_project', sa.Column('archived', sa.Boolean(), nullable=True))
    # op.create_unique_constraint('project_name_uc', 'portfolio_project', ['id', 'name'])
    # op.drop_column('web_site_info', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('web_site_info', sa.Column('role', sa.VARCHAR(length=511), nullable=False))
    # op.drop_constraint('project_name_uc', 'portfolio_project', type_='unique')
    op.drop_column('portfolio_project', 'archived')
    # ### end Alembic commands ###
